import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import styles from './styles.landingpage.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='Navbar '>
          navbar
          <a href="/"> Home</a>
          <a href="landingpage"> LDP</a>
          {/* <a href="Home"> </a> */}
        </nav>
        {children}
      </body>
    </html>
  )
}
